export const PROMISES_KEPT_HINTS: Record<number, string> = {
  1: "👀❤️ Wait 3 seconds, then gently tap the heart.",
  2: "⏳ Don't rush. Wait for the YES button to activate.",
  3: "🥺 Follow the emoji with your finger. Don't tap it.",
  4: "🔐 Hold the heart for 7 full seconds. Patience.",
  5: "🧘‍♂️ Hold your finger steady anywhere on screen.",
  6: "📖 Read carefully. Tap the instruction text itself.",
  7: "⏱️ Let the countdown finish. Don't touch anything.",
  8: "💞 One heart is fading. Choose that one.",
  9: "☔ Drag the umbrella to protect the heart from rain.",
  10: "🤍 Long press anywhere. Just be present.",
  
  11: "🧠 Don't tap the button. Tap the background instead.",
  12: "😤➡️😌 Wait patiently until the anger fades.",
  13: "🔍❤️ Look carefully. Tap the smallest heart.",
  14: "📝❌ Drag the moving text off the screen.",
  15: "🌫️ Drag the shadow away from the button.",
  16: "🐢 It says tap fast, but trust yourself. Tap slowly.",
  17: "😌 Ignore the rushing timer. Just wait.",
  18: "🔇 Mute all the sound icons to bring silence.",
  19: "🛤️ Choose the longer path. Effort matters.",
  20: "🧘‍♀️ Don't touch the screen. Stay steady.",
  
  21: "🕯️💨❤️ Hold your finger over the candle to block the wind.",
  22: "💧❤️ Let the first tears fall. Tap only the last one.",
  23: "❤️⏳ Wait until the heart is completely filled, then tap it.",
  24: "🧩💔➡️❤️ Drag the pieces carefully into the right positions.",
  25: "⏳🤍 Ignore the 'tap to speed up' text. Let it load naturally.",
  26: "🌙🎯 Tap the exact center when the moon aligns with it.",
  27: "🚪⏱️ Count the door openings. Tap on the 3rd one only.",
  28: "✨🧠 Don't react to the first flash. Wait for the second.",
  29: "💡🖤❤️ Drag the light bulb off screen to reveal the heart.",
  30: "🎵🔇 Tap the mute icon, then wait 2 seconds.",
  
  31: "😠➡️😌 Don't engage with anger. Wait for calm.",
  32: "🎁❌🤗✅ Choose the hug, not the gift. Love over things.",
  33: "❓❓ The question appears twice. Answer the second time.",
  34: "🤫⏳ Respect the silence. Wait 10 seconds without touching.",
  35: "🎭❤️ Ignore the 'YOU WIN' text. Find the hidden heart.",
  36: "✏️❤️ Swipe to erase the word 'Broken' from the promise.",
  37: "😌 Wait for the emojis to stop rotating, then tap the calm one.",
  38: "🔁⏳ Don't panic. Let the timer restart twice.",
  39: "❤️🎵 Feel the rhythm. Tap between the heartbeats.",
  40: "📐✨ Double-tap the bottom-right corner.",
  
  41: "🔁❌ Don't tap the Retry button. Tap the background.",
  42: "🧠❤️ Remember the instruction that flashed. Tap and hold.",
  43: "✋❄️ Long press the screen to freeze all moving objects.",
  44: "📝➡️ Drag the floating text off the screen.",
  45: "⬛✨ Don't tap the center. Tap the blinking border.",
  46: "⏱️❌ Ignore the rushing timer completely.",
  47: "🌑➡️🌕 Drag the brightness slider all the way up.",
  48: "2️⃣❤️ Wait 2 seconds, then tap the second button.",
  49: "💔➡️❤️ Don't interrupt the healing. Wait for cracks to disappear.",
  50: "👁️✨ Wait for the button to fade, then tap when it's very dim.",
  
  51: "⏳🤍 Don't leave. Wait 15 seconds for the circle to glow.",
  52: "😢➡️😌 Stay until the crying animation completes fully.",
  53: "📐👀 Tap exactly on the left edge of the screen.",
  54: "❤️🎶 Match the rhythm. Tap between the heartbeats.",
  55: "✋📜 Long press the fading text to make it visible again.",
  56: "🫂➡️🌫️ Don't tap the comfort button. Give space.",
  57: "🌊✋ Place your finger on center and hold to block the waves.",
  58: "🪟😌 Don't panic at the cracks. Wait for them to vanish.",
  59: "💧🎯 Let the tears fall. Tap only the final one.",
  60: "🤍🌌 Know when to stop. Do nothing for 10 seconds.",
  
  61: "🚫📝 Don't trust the hint. Tap after it disappears.",
  62: "🔄💔 Accept failure. This level requires losing first.",
  63: "🔁❤️ Don't fear trying again. Tap Retry immediately.",
  64: "🕊️🤍 Trust without proof. Do nothing at all.",
  65: "🔍✨ Notice the small signs. Long press top-left corner.",
  66: "❤️✨❌ Choose real over flashy. Tap the dull heart.",
  67: "⏳👁️ Wait for clarity. Buttons will return, then choose.",
  68: "🔔👂 Listen carefully. Tap only after the sound plays.",
  69: "🔄❌ Break the habit. On the 4th repeat, tap differently.",
  70: "🧠❤️ Remember Level 10. Repeat that exact action.",
  
  71: "⚪👆 Focus. Wait 3 seconds, then tap the dot.",
  72: "📝⬇️ Move words gently. Drag the word downward.",
  73: "🤍✋ Feel the presence. Long press the center.",
  74: "📏➡️ Follow till the end. Tap where the line finishes.",
  75: "❤️📈 Help it grow. Long press to enlarge the heart.",
  76: "✨🌑 Choose subtle love. Tap the glow at its dimmest.",
  77: "⬇️🖤 Move with intention. Swipe downward slowly.",
  78: "🎧⏳ Let moments complete. Wait for the sound to end.",
  79: "🌬️❤️ Breathe together. Tap when the icon is fully expanded.",
  80: "🤍♾️ Peace needs nothing. Just be.",
  
  81: "❤️🧭 Trust your heart. Wait 5 seconds, then tap.",
  82: "🧠✨ You've learned. Observe first, act second.",
  83: "🎬❌ Don't quit early. Tap behind 'THE END' text.",
  84: "⏱️✋ Balance time and touch. Long press when timer = 2.",
  85: "❤️⚡ Don't miss the moment. Tap the heart instantly.",
  86: "🎯😌 Stay focused. Tap center only when distractions stop.",
  87: "⏳🧠 Remember patience. Let the countdown finish.",
  88: "📐👣 Explore quietly. Tap the bottom-left edge.",
  89: "❤️🔒 Hold on till it's real. Long press until full glow.",
  90: "♾️💍 You didn't solve puzzles. You kept promises.",
  
  91: "❤️🧭 No instructions. Trust your heart. Wait, then tap.",
  92: "🧠✨ You've learned everything. Observe, then act.",
  93: "🎬❌ Don't quit. Tap behind the text.",
  94: "⏱️✋ Balance. Long press when the timer reaches 2.",
  95: "❤️⚡ Don't miss it. Tap the heart the moment it appears.",
  96: "🎯😌 Stay focused. Wait for stillness, then tap center.",
  97: "⏳🧠 Remember. Let the countdown complete.",
  98: "📐👣 Explore. Tap the bottom-left edge.",
  99: "❤️🔒 Hold on. Long press until the heart glows fully.",
  100: "♾️💍 You kept every promise. Just be present.",
};

export function getPromisesKeptHint(levelNumber: number): string {
  return PROMISES_KEPT_HINTS[levelNumber] || "💭 Follow your heart.";
}
