/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const LevelState = IDL.Record({
  'lastUnlockedLevel' : IDL.Nat,
  'completedLevels' : IDL.Vec(IDL.Nat),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLevelState' : IDL.Func([], [LevelState], ['query']),
  'getPromisesKeptLevelState' : IDL.Func([], [LevelState], ['query']),
  'getPromisesKeptUserLevelState' : IDL.Func(
      [IDL.Principal],
      [LevelState],
      ['query'],
    ),
  'getQuizLevelState' : IDL.Func([], [LevelState], ['query']),
  'getQuizUserLevelState' : IDL.Func([IDL.Principal], [LevelState], ['query']),
  'getUserLevelState' : IDL.Func([IDL.Principal], [LevelState], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'resetProgress' : IDL.Func([], [], []),
  'resetPromisesKeptProgress' : IDL.Func([], [], []),
  'resetQuizProgress' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCompletedLevel' : IDL.Func([IDL.Nat], [LevelState], []),
  'savePromisesKeptLevelCompleted' : IDL.Func([IDL.Nat], [LevelState], []),
  'saveQuizLevelCompleted' : IDL.Func([IDL.Nat], [LevelState], []),
  'unlockLevel' : IDL.Func([IDL.Nat], [LevelState], []),
  'unlockPromisesKeptLevel' : IDL.Func([IDL.Nat], [LevelState], []),
  'unlockQuizLevel' : IDL.Func([IDL.Nat], [LevelState], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const LevelState = IDL.Record({
    'lastUnlockedLevel' : IDL.Nat,
    'completedLevels' : IDL.Vec(IDL.Nat),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLevelState' : IDL.Func([], [LevelState], ['query']),
    'getPromisesKeptLevelState' : IDL.Func([], [LevelState], ['query']),
    'getPromisesKeptUserLevelState' : IDL.Func(
        [IDL.Principal],
        [LevelState],
        ['query'],
      ),
    'getQuizLevelState' : IDL.Func([], [LevelState], ['query']),
    'getQuizUserLevelState' : IDL.Func(
        [IDL.Principal],
        [LevelState],
        ['query'],
      ),
    'getUserLevelState' : IDL.Func([IDL.Principal], [LevelState], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'resetProgress' : IDL.Func([], [], []),
    'resetPromisesKeptProgress' : IDL.Func([], [], []),
    'resetQuizProgress' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCompletedLevel' : IDL.Func([IDL.Nat], [LevelState], []),
    'savePromisesKeptLevelCompleted' : IDL.Func([IDL.Nat], [LevelState], []),
    'saveQuizLevelCompleted' : IDL.Func([IDL.Nat], [LevelState], []),
    'unlockLevel' : IDL.Func([IDL.Nat], [LevelState], []),
    'unlockPromisesKeptLevel' : IDL.Func([IDL.Nat], [LevelState], []),
    'unlockQuizLevel' : IDL.Func([IDL.Nat], [LevelState], []),
  });
};

export const init = ({ IDL }) => { return []; };