export const LEVEL_HINTS: Record<number, string> = {
  1: "Don't tap the heart... tap the instruction text instead! 💭",
  2: "Drag the sun downward to make it night. 🌅",
  3: "Hold the envelope for 1.5 seconds without releasing. 💌",
  4: "Tap the hearts to make them move, then count them carefully and enter the number. 🔢",
  5: "Drag the grey Start button upward to activate it. ⬆️",
  6: "Drag the pillow away from the sleeping girl's face. 🛏️",
  7: "Double-tap the light bulb to turn it off. 💡",
  8: "Drag the smile piece onto the face to fix it. 😊",
  9: "Swipe across the screen to clean away the dirt overlay. 🧹",
  10: "Press and hold the heart button for 2 seconds. ❤️",
  
  11: "Remove the pillow covering the alarm clock. ⏰",
  12: "Drag the two heart halves together to fix the broken heart. 💔➡️💖",
  13: "Tap the gift boxes - fake ones will fade, find the real one! 🎁",
  14: "Hold the toggle switch for 1.5 seconds to turn on love. 🔛",
  15: "Use the eraser to erase the word 'SAD'. ✏️",
  16: "Drag the keyhole, not the door! 🔑",
  17: "Drag the umbrella under the raining cloud. ☂️",
  18: "Drag the bowl down to the cat to feed it. 🐱",
  19: "Swipe LEFT on the book (wrong direction is right!). 📖",
  20: "Drag the heart slowly - if you go too fast, you'll fail! 🐌",
  
  21: "The Continue button is fake - tap the background instead. 🎭",
  22: "Wait for the YES button to stop moving, then tap it. ⏱️",
  23: "Swipe the popup downward to close it. 👇",
  24: "Drag the volume icon itself, not the slider. 🔊",
  25: "Drag the instruction text away to reveal the solution. 📝",
  26: "Look for the heart icon in the UI (top right) and tap it. ❤️",
  27: "Tap the page number, not the page itself. 📄",
  28: "Find and tap the pause icon in the UI bar. ⏸️",
  29: "Drag the frame border to align it properly. 🖼️",
  30: "Long press the top-left corner to open the menu. 📍",
  
  31: "Give her the flower - the other gifts won't work. 🌹",
  32: "Drag the hands under the eyes to catch the tears. 😢",
  33: "Drag the shield over the flame to protect it from wind. 🛡️",
  34: "Remove all the distracting objects by tapping them. 📱",
  35: "Click to balance the scale perfectly. ⚖️",
  36: "Hold anywhere on the screen for 3 seconds to calm down. 🧘",
  37: "Choose the correct promise - only one is true. 🤝",
  38: "Build trust by waiting 3 seconds without touching anything. ⏰",
  39: "Drag the shadow away from the person. 👤",
  40: "Rub the screen left and right to warm the hands. 🤲",
  
  41: "Don't touch anything - just wait 3 seconds. 🚫",
  42: "Tap exactly when the timer shows the target second. ⏱️",
  43: "Wait for the storm to calm down naturally. 🌪️",
  44: "Wait at least 2 seconds before tapping slowly. 🐌",
  45: "Let the objects settle - wait without clicking. 📦",
  46: "Patience test - just wait for the timer. ⏰",
  47: "Hold the button for 2 seconds. 🔘",
  48: "Tap at the right moment (between 2-4 seconds). ⏱️",
  49: "Wait for the character to blink, then tap. 😉",
  50: "Wait for the mute icon to appear. 🔇",
  
  51: "Wait for the OK button to appear after 2 seconds. ✅",
  52: "Drag the lock away, not the key. 🔒",
  53: "Pinch or click to resize the UI panel. 🔍",
  54: "Drag the text label obstacle away. 🚧",
  55: "Long press the background to reveal hidden option. 🔍",
  56: "Remove the overlay layer by tapping it. 👆",
  57: "Click to rotate the UI element. 🔄",
  58: "Scroll down in the invisible scroll area. 📜",
  59: "Find and tap the checkmark icon. ✓",
  60: "Find and tap the undo icon. ↶",
  
  61: "Complete step 1 first, then step 2 - order matters! 1️⃣2️⃣",
  62: "Calm the character first, then tap. 🧘➡️👆",
  63: "Combine the items, then use them. 🧩",
  64: "Disable the noise first, then solve. 🔇➡️✓",
  65: "Fix the error, then continue. 🔧➡️▶️",
  66: "Charge the heart first, then tap it. ⚡➡️❤️",
  67: "Rotate the key, then unlock. 🔑➡️🔓",
  68: "Clean the screen to reveal the button. 🧹➡️🔘",
  69: "Arrange the objects, then confirm. 📐➡️✓",
  70: "Prepare first, then act. 🎯➡️🎬",
  
  71: "The instruction lies - do the opposite! 🎭",
  72: "Do nothing - literally just wait. 🧘",
  73: "Wait for the new circle to appear, then tap it. ⏱️",
  74: "You need to fail once first to unlock the win. 🔄",
  75: "Look for a hidden button on the lose screen. 🔍",
  76: "Find and tap the specific word in the text. 📝",
  77: "Tap the empty area - something invisible is there. 👻",
  78: "Just wait - you'll win after a delay. ⏰",
  79: "Tap the background element, not the foreground. 🎨",
  80: "Tap the very edge of the screen. 📍",
  
  81: "Drag all the photos into the collage. 📸",
  82: "Match the letters to spell LOVE. 🔤",
  83: "Merge the two photo pieces together. 🖼️",
  84: "Choose any true promise - they all work. 💝",
  85: "Block the falling objects to protect the heart. 🛡️",
  86: "Hold both hands together (tap both). 🤝",
  87: "Just a minimal tap anywhere. ✨",
  88: "Swipe gently and slowly. 👆",
  89: "Hold without moving your finger at all. 🤫",
  90: "Drag the memory icon into the heart. 💫",
  
  91: "Complete multiple steps with patience. 🎯",
  92: "Combine UI interaction with timing. ⏱️",
  93: "Follow your heart - tap it! ❤️",
  94: "This isn't the real ending - tap anywhere to continue. 🎭",
  95: "Trust the process and wait. 🤝",
  96: "Tap when the timer is divisible by 3. ⏰",
  97: "Move all the objects by tapping them. 🌍",
  98: "Only the text works - tap the instruction! 📝",
  99: "Find the tiny dot and tap it. 🔴",
  100: "Use everything you've learned - tap the heart! 💖",
};

export function getHintForLevel(levelNumber: number): string {
  return LEVEL_HINTS[levelNumber] || "Think outside the box! 💭";
}
